### List All Resource
GET http://localhost:3000/v1/tasks

### Getting a Resource
GET http://localhost:3000/v1/tasks/2

### Creating a Resource
POST http://localhost:3000/v1/tasks
Content-Type: application/json

{
    "description": "test baru",
    "deadline": "test baru",
    "priority": 2,
    "is_completed": true
}

### Updating a resource
PUT http://localhost:3000/v1/tasks/11
Content-Type: application/json

{
    "description": "test baru",
    "deadline": "test baru",
    "priority": 2,
    "is_completed": true
}

### Deleting a Resource
DELETE http://localhost:3000/v1/tasks/10